import { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "ru" | "vi";

const translations = {
  en: {
    forgotPassword: {
      title: "Forgot Password",
      subtitle: "Enter your email and we'll generate a reset link",
      email: "Email",
      emailPlaceholder: "you@example.com",
      sendBtn: "Generate Reset Link",
      sending: "Generating...",
      backToLogin: "← Back to login",
      sent: "Check your email",
      sentDesc: "If this email is registered, a reset link was generated.",
      tokenReady: "Reset link generated successfully",
      yourLink: "Your reset link (valid 1 hour):",
      noEmailNote: "No email service configured. Copy and open this link manually.",
      expiresIn: "Link expires in 1 hour",
      error: "Something went wrong",
    },
    resetPassword: {
      title: "Reset Password",
      subtitle: "Enter your new password",
      newPassword: "New Password",
      passwordPlaceholder: "Min. 6 characters",
      confirmPassword: "Confirm Password",
      confirmPlaceholder: "Repeat password",
      saveBtn: "Save New Password",
      saving: "Saving...",
      invalidTitle: "Link invalid or expired",
      invalidDesc: "This reset link has already been used or has expired.",
      requestNew: "Request a new link",
      successTitle: "Password changed!",
      successDesc: "Redirecting to login...",
      passNoMatch: "Passwords do not match",
      passShort: "Password must be at least 6 characters",
      error: "Reset failed",
    },
    nav: {
      marketplace: "Marketplace",
      dashboard: "Dashboard",
      admin: "Admin",
      listVehicle: "+ List Vehicle",
      login: "Login",
      signUp: "Sign Up Free",
      logout: "Logout",
      adminPanel: "Admin Panel",
      upgrade: "Upgrade to Business",
      listVehicleMenu: "List a Vehicle",
    },
    home: {
      badge: "Nha Trang, Vietnam",
      heroTitle1: "Rent the Perfect",
      heroTitle2: "Ride in Nha Trang",
      heroDesc: "Explore Vietnam's most beautiful coastal city on two wheels. From electric VinFast bikes to classic scooters — find your perfect rental from local owners.",
      searchPlaceholder: "Search bikes, brands, models...",
      searchBtn: "Search",
      verified: "Verified owners",
      instant: "Instant booking",
      bestPrice: "Best prices",
      filter: "Filter:",
      all: "All",
      bikes: "Bikes",
      scooters: "Scooters",
      cars: "Cars",
      electric: "Electric",
      petrol: "Petrol",
      clearFilters: "Clear filters",
      featured: "Featured Listings",
      featuredSub: "Top picks from verified owners",
      allVehicles: "All Vehicles",
      searchResults: "Search Results",
      available: "available",
      noVehicles: "No vehicles found",
      noVehiclesDesc: "Try adjusting your filters or search terms to find available vehicles.",
      clearAll: "Clear all filters",
      footerSub: "P2P Vehicle Rental — Nha Trang, Vietnam",
      footerRights: "© 2025 RentMyBike. All rights reserved.",
    },
    login: {
      welcome: "Welcome back",
      subtitle: "Sign in to your account to continue",
      username: "Username",
      usernamePlaceholder: "Enter your username",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      signIn: "Sign In",
      signingIn: "Signing in...",
      noAccount: "Don't have an account?",
      createOne: "Create one free",
      demo: "Demo accounts:",
      invalidCredentials: "Invalid credentials",
      forgotPassword: "Forgot password?",
    },
    register: {
      title: "Create an account",
      subtitle: "Start renting and listing vehicles for free",
      fullName: "Full Name",
      phone: "Phone (optional)",
      username: "Username",
      usernamePlaceholder: "Choose a unique username",
      email: "Email",
      emailPlaceholder: "you@example.com",
      password: "Password",
      passwordPlaceholder: "Min. 6 characters",
      confirmPassword: "Confirm Password",
      confirmPlaceholder: "Repeat password",
      createBtn: "Create Free Account",
      creating: "Creating account...",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      freePlan: "Free accounts include 1 vehicle listing. Upgrade to Business for unlimited listings.",
      passNoMatch: "Passwords do not match",
      passShort: "Password must be at least 6 characters",
      failed: "Registration failed",
    },
    admin: {
      title: "Admin Control Center",
      subtitle: "RentMyBike Platform Management",
      totalUsers: "Total Users",
      business: "Business",
      activeVehicles: "Active Vehicles",
      pendingReview: "Pending Review",
      bookings: "Bookings",
      revenue: "Revenue",
      pendingPayments: "Pending Payments",
      vehiclesTab: "Vehicles",
      paymentsTab: "Payments",
      usersTab: "Users",
      pending: "Pending",
      active: "Active",
      rejected: "Rejected",
      noVehicles: "No vehicles",
      noPayments: "No payment requests yet",
      featured: "Featured",
      feature: "Feature",
      unfeature: "Unfeature",
      owner: "Owner",
      approve: "Approve",
      reject: "Reject",
      viewProof: "View proof",
      updated: "Updated",
      joined: "Joined",
      upgradeToBusiness: "Upgrade to Business",
      downgradeToFree: "Downgrade to Free",
      makeAdmin: "Make Admin",
      removeAdmin: "Remove Admin",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome back",
      upgradeBtn: "Upgrade to Business",
      addVehicle: "Add Vehicle",
      myVehicles: "My Vehicles",
      activeListings: "Active Listings",
      pendingBookings: "Pending Bookings",
      totalEarnings: "Total Earnings",
      freeLimitTitle: "Free plan limit reached",
      freeLimitDesc: "Upgrade to Business to list unlimited vehicles and get priority placement.",
      upgrade: "Upgrade",
      myListings: "My Listings",
      bookingRequests: "Booking Requests",
      myRentals: "My Rentals",
      noVehicles: "No vehicles yet",
      noVehiclesDesc: "List your first vehicle to start earning",
      addFirst: "Add Your First Vehicle",
      noBookingRequests: "No booking requests yet",
      noBookingRequestsDesc: "Requests for your vehicles will appear here",
      noRentals: "No rentals yet",
      noRentalsDesc: "Browse the marketplace and book your first ride!",
      browse: "Browse Vehicles",
      from: "From:",
      confirm: "Confirm",
      decline: "Decline",
      deleteTitle: "Delete this vehicle?",
      deleteDesc: "This will permanently remove the listing from the marketplace.",
      cancel: "Cancel",
      delete: "Delete",
      vehicleDeleted: "Vehicle deleted",
      bookingUpdated: "Booking updated",
    },
  },
  ru: {
    forgotPassword: {
      title: "Забыл пароль",
      subtitle: "Введите email — сгенерируем ссылку для сброса",
      email: "Email",
      emailPlaceholder: "you@example.com",
      sendBtn: "Сгенерировать ссылку",
      sending: "Генерация...",
      backToLogin: "← Назад к входу",
      sent: "Проверьте email",
      sentDesc: "Если email зарегистрирован, ссылка для сброса была сгенерирована.",
      tokenReady: "Ссылка успешно сгенерирована",
      yourLink: "Ваша ссылка для сброса (действует 1 час):",
      noEmailNote: "Email-сервис не настроен. Скопируйте и откройте ссылку вручную.",
      expiresIn: "Ссылка истекает через 1 час",
      error: "Что-то пошло не так",
    },
    resetPassword: {
      title: "Новый пароль",
      subtitle: "Введите новый пароль",
      newPassword: "Новый пароль",
      passwordPlaceholder: "Мин. 6 символов",
      confirmPassword: "Подтвердите пароль",
      confirmPlaceholder: "Повторите пароль",
      saveBtn: "Сохранить пароль",
      saving: "Сохранение...",
      invalidTitle: "Ссылка недействительна или истекла",
      invalidDesc: "Эта ссылка уже использована или срок её действия истёк.",
      requestNew: "Запросить новую ссылку",
      successTitle: "Пароль изменён!",
      successDesc: "Перенаправление на страницу входа...",
      passNoMatch: "Пароли не совпадают",
      passShort: "Пароль должен содержать минимум 6 символов",
      error: "Ошибка сброса пароля",
    },
    nav: {
      marketplace: "Маркетплейс",
      dashboard: "Кабинет",
      admin: "Админ",
      listVehicle: "+ Добавить",
      login: "Войти",
      signUp: "Регистрация",
      logout: "Выйти",
      adminPanel: "Панель администратора",
      upgrade: "Перейти на Бизнес",
      listVehicleMenu: "Добавить транспорт",
    },
    home: {
      badge: "Нячанг, Вьетнам",
      heroTitle1: "Арендуй лучший",
      heroTitle2: "транспорт в Нячанге",
      heroDesc: "Исследуй самый красивый прибрежный город Вьетнама на двух колёсах. Электробайки VinFast и классические скутеры — найди идеальную аренду у местных владельцев.",
      searchPlaceholder: "Поиск байков, брендов, моделей...",
      searchBtn: "Найти",
      verified: "Проверенные владельцы",
      instant: "Мгновенное бронирование",
      bestPrice: "Лучшие цены",
      filter: "Фильтр:",
      all: "Все",
      bikes: "Байки",
      scooters: "Скутеры",
      cars: "Авто",
      electric: "Электро",
      petrol: "Бензин",
      clearFilters: "Сбросить",
      featured: "Рекомендуемые",
      featuredSub: "Лучший выбор от проверенных владельцев",
      allVehicles: "Весь транспорт",
      searchResults: "Результаты поиска",
      available: "доступно",
      noVehicles: "Транспорт не найден",
      noVehiclesDesc: "Попробуйте изменить фильтры или поисковый запрос.",
      clearAll: "Сбросить все фильтры",
      footerSub: "P2P аренда транспорта — Нячанг, Вьетнам",
      footerRights: "© 2025 RentMyBike. Все права защищены.",
    },
    login: {
      welcome: "С возвращением",
      subtitle: "Войдите в свой аккаунт, чтобы продолжить",
      username: "Имя пользователя",
      usernamePlaceholder: "Введите имя пользователя",
      password: "Пароль",
      passwordPlaceholder: "Введите пароль",
      signIn: "Войти",
      signingIn: "Вход...",
      noAccount: "Нет аккаунта?",
      createOne: "Создать бесплатно",
      demo: "Демо аккаунты:",
      invalidCredentials: "Неверные данные",
      forgotPassword: "Забыли пароль?",
    },
    register: {
      title: "Создать аккаунт",
      subtitle: "Начните аренду и размещение транспорта бесплатно",
      fullName: "Полное имя",
      phone: "Телефон (необязательно)",
      username: "Имя пользователя",
      usernamePlaceholder: "Выберите уникальный логин",
      email: "Email",
      emailPlaceholder: "you@example.com",
      password: "Пароль",
      passwordPlaceholder: "Мин. 6 символов",
      confirmPassword: "Подтвердите пароль",
      confirmPlaceholder: "Повторите пароль",
      createBtn: "Создать аккаунт",
      creating: "Создание...",
      haveAccount: "Уже есть аккаунт?",
      signIn: "Войти",
      freePlan: "Бесплатный аккаунт включает 1 объявление. Перейдите на Бизнес для неограниченного размещения.",
      passNoMatch: "Пароли не совпадают",
      passShort: "Пароль должен содержать минимум 6 символов",
      failed: "Ошибка регистрации",
    },
    admin: {
      title: "Панель администратора",
      subtitle: "Управление платформой RentMyBike",
      totalUsers: "Всего пользователей",
      business: "Бизнес",
      activeVehicles: "Активных транспорт",
      pendingReview: "На проверке",
      bookings: "Бронирований",
      revenue: "Доход",
      pendingPayments: "Ожидают оплаты",
      vehiclesTab: "Транспорт",
      paymentsTab: "Платежи",
      usersTab: "Пользователи",
      pending: "На проверке",
      active: "Активные",
      rejected: "Отклонённые",
      noVehicles: "Нет транспорта",
      noPayments: "Нет запросов на оплату",
      featured: "Рекомендуемый",
      feature: "Рекомендовать",
      unfeature: "Убрать",
      owner: "Владелец",
      approve: "Одобрить",
      reject: "Отклонить",
      viewProof: "Посмотреть подтверждение",
      updated: "Обновлено",
      joined: "Регистрация",
      upgradeToBusiness: "Повысить до Бизнес",
      downgradeToFree: "Понизить до Бесплатного",
      makeAdmin: "Сделать администратором",
      removeAdmin: "Убрать администратора",
    },
    dashboard: {
      title: "Личный кабинет",
      welcome: "С возвращением",
      upgradeBtn: "Перейти на Бизнес",
      addVehicle: "Добавить транспорт",
      myVehicles: "Мой транспорт",
      activeListings: "Активных объявлений",
      pendingBookings: "Ожидают подтверждения",
      totalEarnings: "Общий доход",
      freeLimitTitle: "Достигнут лимит бесплатного плана",
      freeLimitDesc: "Перейдите на Бизнес для неограниченного размещения и приоритетного показа.",
      upgrade: "Обновить",
      myListings: "Мои объявления",
      bookingRequests: "Запросы на бронирование",
      myRentals: "Мои аренды",
      noVehicles: "Нет объявлений",
      noVehiclesDesc: "Добавьте первый транспорт, чтобы начать зарабатывать",
      addFirst: "Добавить первый транспорт",
      noBookingRequests: "Нет запросов на бронирование",
      noBookingRequestsDesc: "Запросы для вашего транспорта будут отображаться здесь",
      noRentals: "Нет аренд",
      noRentalsDesc: "Просмотрите маркетплейс и забронируйте первую поездку!",
      browse: "Смотреть транспорт",
      from: "От:",
      confirm: "Подтвердить",
      decline: "Отклонить",
      deleteTitle: "Удалить это объявление?",
      deleteDesc: "Объявление будет навсегда удалено из маркетплейса.",
      cancel: "Отмена",
      delete: "Удалить",
      vehicleDeleted: "Объявление удалено",
      bookingUpdated: "Бронирование обновлено",
    },
  },
  vi: {
    forgotPassword: {
      title: "Quên Mật Khẩu",
      subtitle: "Nhập email để tạo liên kết đặt lại mật khẩu",
      email: "Email",
      emailPlaceholder: "you@example.com",
      sendBtn: "Tạo liên kết đặt lại",
      sending: "Đang tạo...",
      backToLogin: "← Quay lại đăng nhập",
      sent: "Kiểm tra email của bạn",
      sentDesc: "Nếu email đã đăng ký, liên kết đặt lại đã được tạo.",
      tokenReady: "Liên kết đã được tạo thành công",
      yourLink: "Liên kết đặt lại của bạn (có hiệu lực 1 giờ):",
      noEmailNote: "Chưa cấu hình dịch vụ email. Sao chép và mở liên kết thủ công.",
      expiresIn: "Liên kết hết hạn sau 1 giờ",
      error: "Đã xảy ra lỗi",
    },
    resetPassword: {
      title: "Đặt Lại Mật Khẩu",
      subtitle: "Nhập mật khẩu mới của bạn",
      newPassword: "Mật khẩu mới",
      passwordPlaceholder: "Tối thiểu 6 ký tự",
      confirmPassword: "Xác nhận mật khẩu",
      confirmPlaceholder: "Nhập lại mật khẩu",
      saveBtn: "Lưu mật khẩu mới",
      saving: "Đang lưu...",
      invalidTitle: "Liên kết không hợp lệ hoặc đã hết hạn",
      invalidDesc: "Liên kết này đã được sử dụng hoặc đã hết hạn.",
      requestNew: "Yêu cầu liên kết mới",
      successTitle: "Đổi mật khẩu thành công!",
      successDesc: "Đang chuyển hướng đến trang đăng nhập...",
      passNoMatch: "Mật khẩu không khớp",
      passShort: "Mật khẩu phải có ít nhất 6 ký tự",
      error: "Đặt lại mật khẩu thất bại",
    },
    nav: {
      marketplace: "Thị trường",
      dashboard: "Bảng điều khiển",
      admin: "Quản trị",
      listVehicle: "+ Đăng xe",
      login: "Đăng nhập",
      signUp: "Đăng ký miễn phí",
      logout: "Đăng xuất",
      adminPanel: "Bảng quản trị",
      upgrade: "Nâng cấp Kinh doanh",
      listVehicleMenu: "Đăng xe cho thuê",
    },
    home: {
      badge: "Nha Trang, Việt Nam",
      heroTitle1: "Thuê xe hoàn hảo",
      heroTitle2: "tại Nha Trang",
      heroDesc: "Khám phá thành phố biển đẹp nhất Việt Nam bằng hai bánh. Xe điện VinFast và xe tay ga cổ điển — tìm xe thuê hoàn hảo từ chủ xe địa phương.",
      searchPlaceholder: "Tìm xe, hãng, mẫu xe...",
      searchBtn: "Tìm kiếm",
      verified: "Chủ xe đã xác minh",
      instant: "Đặt xe ngay lập tức",
      bestPrice: "Giá tốt nhất",
      filter: "Lọc:",
      all: "Tất cả",
      bikes: "Xe máy",
      scooters: "Xe tay ga",
      cars: "Ô tô",
      electric: "Điện",
      petrol: "Xăng",
      clearFilters: "Xóa bộ lọc",
      featured: "Nổi bật",
      featuredSub: "Lựa chọn hàng đầu từ chủ xe đã xác minh",
      allVehicles: "Tất cả xe",
      searchResults: "Kết quả tìm kiếm",
      available: "có sẵn",
      noVehicles: "Không tìm thấy xe",
      noVehiclesDesc: "Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm.",
      clearAll: "Xóa tất cả bộ lọc",
      footerSub: "Thuê xe P2P — Nha Trang, Việt Nam",
      footerRights: "© 2025 RentMyBike. Bảo lưu mọi quyền.",
    },
    login: {
      welcome: "Chào mừng trở lại",
      subtitle: "Đăng nhập để tiếp tục",
      username: "Tên người dùng",
      usernamePlaceholder: "Nhập tên người dùng",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu",
      signIn: "Đăng nhập",
      signingIn: "Đang đăng nhập...",
      noAccount: "Chưa có tài khoản?",
      createOne: "Tạo miễn phí",
      demo: "Tài khoản demo:",
      invalidCredentials: "Thông tin không hợp lệ",
      forgotPassword: "Quên mật khẩu?",
    },
    register: {
      title: "Tạo tài khoản",
      subtitle: "Bắt đầu thuê và đăng xe miễn phí",
      fullName: "Họ và tên",
      phone: "Điện thoại (tùy chọn)",
      username: "Tên người dùng",
      usernamePlaceholder: "Chọn tên người dùng duy nhất",
      email: "Email",
      emailPlaceholder: "you@example.com",
      password: "Mật khẩu",
      passwordPlaceholder: "Tối thiểu 6 ký tự",
      confirmPassword: "Xác nhận mật khẩu",
      confirmPlaceholder: "Nhập lại mật khẩu",
      createBtn: "Tạo tài khoản miễn phí",
      creating: "Đang tạo...",
      haveAccount: "Đã có tài khoản?",
      signIn: "Đăng nhập",
      freePlan: "Tài khoản miễn phí gồm 1 tin đăng xe. Nâng cấp lên Kinh doanh để đăng không giới hạn.",
      passNoMatch: "Mật khẩu không khớp",
      passShort: "Mật khẩu phải có ít nhất 6 ký tự",
      failed: "Đăng ký thất bại",
    },
    admin: {
      title: "Trung Tâm Quản Trị",
      subtitle: "Quản lý nền tảng RentMyBike",
      totalUsers: "Tổng người dùng",
      business: "Kinh doanh",
      activeVehicles: "Xe đang hoạt động",
      pendingReview: "Chờ duyệt",
      bookings: "Đặt xe",
      revenue: "Doanh thu",
      pendingPayments: "Chờ thanh toán",
      vehiclesTab: "Xe",
      paymentsTab: "Thanh toán",
      usersTab: "Người dùng",
      pending: "Chờ duyệt",
      active: "Đang hoạt động",
      rejected: "Đã từ chối",
      noVehicles: "Không có xe",
      noPayments: "Chưa có yêu cầu thanh toán",
      featured: "Nổi bật",
      feature: "Đặt nổi bật",
      unfeature: "Bỏ nổi bật",
      owner: "Chủ xe",
      approve: "Duyệt",
      reject: "Từ chối",
      viewProof: "Xem bằng chứng",
      updated: "Đã cập nhật",
      joined: "Ngày tham gia",
      upgradeToBusiness: "Nâng cấp Kinh doanh",
      downgradeToFree: "Hạ xuống Miễn phí",
      makeAdmin: "Đặt làm Admin",
      removeAdmin: "Xóa Admin",
    },
    dashboard: {
      title: "Bảng điều khiển",
      welcome: "Chào mừng trở lại",
      upgradeBtn: "Nâng cấp Kinh doanh",
      addVehicle: "Thêm xe",
      myVehicles: "Xe của tôi",
      activeListings: "Tin đang hoạt động",
      pendingBookings: "Chờ xác nhận",
      totalEarnings: "Tổng thu nhập",
      freeLimitTitle: "Đã đạt giới hạn gói miễn phí",
      freeLimitDesc: "Nâng cấp lên Kinh doanh để đăng không giới hạn và được ưu tiên hiển thị.",
      upgrade: "Nâng cấp",
      myListings: "Tin của tôi",
      bookingRequests: "Yêu cầu đặt xe",
      myRentals: "Xe đã thuê",
      noVehicles: "Chưa có xe nào",
      noVehiclesDesc: "Đăng xe đầu tiên để bắt đầu kiếm tiền",
      addFirst: "Thêm xe đầu tiên",
      noBookingRequests: "Chưa có yêu cầu đặt xe",
      noBookingRequestsDesc: "Yêu cầu cho xe của bạn sẽ xuất hiện ở đây",
      noRentals: "Chưa có lần thuê xe nào",
      noRentalsDesc: "Duyệt thị trường và đặt chuyến đi đầu tiên!",
      browse: "Xem xe",
      from: "Từ:",
      confirm: "Xác nhận",
      decline: "Từ chối",
      deleteTitle: "Xóa xe này?",
      deleteDesc: "Tin đăng sẽ bị xóa vĩnh viễn khỏi thị trường.",
      cancel: "Hủy",
      delete: "Xóa",
      vehicleDeleted: "Đã xóa xe",
      bookingUpdated: "Đã cập nhật đặt xe",
    },
  },
};

type Translations = typeof translations.en;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("lang");
    return (saved as Lang) || "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export const langLabels: Record<Lang, string> = {
  en: "EN",
  ru: "RU",
  vi: "VI",
};

export const langFlags: Record<Lang, string> = {
  en: "🇬🇧",
  ru: "🇷🇺",
  vi: "🇻🇳",
};
